### ISSUE TITLE
ToDo list for logging

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3731]
Meta issues:
- [x] #3735
  Log files need to have descriptive words in titles, e.g., the log file with activities should have ActivityLog in the file name
- [x] #3817
  Old log files should be cleaned up

Components/modules/things that need to be logged, in priority order:
- [x] #3732
   ActivityLog - new activities and final updates (as of 1/4/2021, does not include: long running table ops, file share stats, blob emulator delete, etc.)
- [x] #3733
  Azure API requests and responses
- [x] #3734
  Information about new process startup
- [x] Changes to settings 
- [x] #4321
  Changes to app state (window size, minimized, maximized, etc)
- [x] Other Internal errors

Dropped issues:
- [x] ~LHS tree view expanding/collapsing~
- [x] ~ActivityLog - updates to activities~

If an issue does not exist as you work on something, please make it.

This issue should move to the next milestone until all work is done.

**Comment by MRayermannMSFT** [comment]
Closing this issue for now. I think we are done with it.
