### ISSUE TITLE
Improve logging & tracing for key scenarios (Verbose Mode)

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#399]
#### Expected Experience: ####
Helpful logging for key scenarios (Start Up, Login, RHS Open, Upload, Download)

#### Actual Experience: ####
Limited logging

#### Potential Solution: ####
"Enable Verbose Logging" Option

## Tasks

- [x] Inject SDK into main and renderer processes
- [x] Add logging definitions to SDK
- [x] Add logging to SDK implementation
- [ ] Add command line switches for log level

**Comment by JakeRadMSFT** [comment]
Potentially in the Activity Log for "non-developers"

**Comment by RobertBernstein** [comment]
This logging would also be useful in scenarios where users are prohibited from installing the OpenSSL tooling in order to perform certificate troubleshooting.

**Comment by craxal** [comment]
Not entirely sure why this items was closed, as nothing except preliminary code has actually been merged yet.

**Comment by legra-ms** [comment]
+1.  Being able to log these events whether it's a text file or via OS-level logging would be extremely useful in auditing user activity for event log aggregation.

**Comment by craxal** [comment]
Core logging work is merged, but logs may be sparse until we convert old diagnostic messages.
