### ISSUE TITLE
Improve authorization error message when storage account firewall is enabled

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#4420]
### Problem

If the firewall is enabled on a storage account and you are connecting to the storage account from a machine whose IP address has not been added to the firewall allow list, then Storage will return an HTTP 403 Authorization error.  Two common scenarios where the firewall settings are the cause of the 403 are when the customer is connecting from the Azure Portal and Storage Explorer.  We asked the Azure portal to update their error message to indicate this could be due to the firewall settings.  This has dramatically cut down the support cases being opened for this issue.

### Desired Solution

I would like to ask if Storage Explorer can also update the error message that they are showing so we can prevent some of these support cases from being opened.  Here is the current Azure Portal Error message.  The Learn more link is http://go.microsoft.com/fwlink/?LinkId=845443.  It is where customers can learn how to configure the storage account firewall and VNET settings.

![pic1](https://user-images.githubusercontent.com/10081483/117184114-38cec100-ad8d-11eb-8440-c1375febd4a5.png)

### Additional Context

Here is the current error that Storage Explorer is showing.  My suggestion would be to use the error details section at the top to mention that the firewall and virtual network settings on the storage account could be the cause.
![pic2](https://user-images.githubusercontent.com/10081483/117184194-4d12be00-ad8d-11eb-85fc-98cfe976eb0e.png)

This request came from Brian Roder.

### Tasks

- [x] Introduce firewall information in Error Details dialog.
- [ ] Use firewall info for auth errors in listing blob containers.
- [ ] Use firewall info for auth errors in listing file shares.
- [ ] Use firewall info for auth errors in listing queues.
- [ ] Use firewall info for auth errors in listing tables.
- [ ] Improve presentation of firewall information.

**Comment by jinglouMSFT** [comment]
If the firewall is enabled on a storage account and you are connecting to the storage account from a machine whose IP address has not been added to the firewall allow list then storage will return an HTTP 403 Authorization error.  Two common scenarios where the firewall settings are the cause of the 403 are when the customer is connecting from the Azure Portal and Storage Explorer.  We asked the Azure portal to update their error message to indicate this could be due to the firewall settings.  This has dramatically cut down the support cases being opened for this issue.  I would like to ask if Storage Explorer can also update the error message that they are showing so we can prevent some of these support cases from being opened.  Here is the current Azure Portal Error message.  The Learn more link is http://go.microsoft.com/fwlink/?LinkId=845443.  It is where customers can learn how to configure the storage account firewall and VNET settings.
![pic1](https://user-images.githubusercontent.com/10081483/117184114-38cec100-ad8d-11eb-8440-c1375febd4a5.png)
Here is the current error that Storage Explorer is showing.  My suggestion would be to use the error details section at the top to mention that the firewall and virtual network settings on the storage account could be the cause.
![pic2](https://user-images.githubusercontent.com/10081483/117184194-4d12be00-ad8d-11eb-85fc-98cfe976eb0e.png)

**Comment by MRayermannMSFT** [comment]
Meet with Brian/CSS team, get feedback on current experience, see if they think the limited experience we added in November seemed to have enough desired effect. If so, talk to them about what service they think we should add to next and then we can do that service in 1.25.

If the limited experience was not good enough, then work with them to iterate on the experience.

**Comment by craxal** [comment]
Brian and his team do not have a good way of correlating the number of cases with then error message other than watching to see if there are fewer cases where adjusting firewall settings resolves issues. I'm going to close this, but we can revisit whenever we get more data.
