### ISSUE TITLE
Deeplinks for attaching/downloading

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#4459]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I need to be able to share links with other people that will let them easily download files in Azure Storage that they have access to, without having to resort to SAS tokens/public access.

### Desired Solution

I'd like a link I can share with people that when clicked would:
1. Open Storage Explorer
2. Attach a resource (a container) via Azure AD if not already attached
3. Have the option to go to a directory or file (and if a file, initiate a download of that file)

### Alternatives and Workarounds

None.

### Additional Context

None.

# TODOs:

- [x] Create new DeepLinkManager/IDeepLinkHandler
- [x] Skeleton AzureAdAttachDeepLinkHandler
- [x] Refactor old deep link handlers
- [x] Flesh out connect flow
- [x] Flesh out download flow
- [x] Better logging and try catching while iterating handlers
- [x] Add command to gen2 explorer
- [x] Incorporate feedback
   - [x] Distinct options for target vs root attach
   - [x] Distinct options for download vs download & open
   - [x] Handle if root attachment already exists
   - [x] Handle if target attachment already exists
   - [x] Remove tenant dropdown
   - [x] Change strings 
- [x] Fix direct links to things in root not working
- [x] Test paths with encodable chars
- [x] Stretch: add action blob container node actions for gen2 nodes
