### ISSUE TITLE
Build and integrate table explorer in React

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#6026]
```[tasklist]
### Tasks
- [x] Add `off` function for content functions in explorer host proxy
- [x] https://github.com/microsoft/AzureStorageExplorer/issues/6473
- [x] Add data grid to table explorer
- [x] Build toolbar in React
- [x] Add toolbar to React table explorer
- [x] [Poachable] Reimplement import command in React table explorer
- [x] [Poachable] Reimplement export commands in React table explorer
- [x] [Poachable] Reimplement add entity command in React table explorer
- [x] [Poachable] Reimplement edit entity command in React table explorer
- [x] [Poachable] Reimplement selection all commands in React table explorer
- [x] [Poachable] Reimplement column options command in React table explorer
- [x] [Poachable] Reimplement delete entities command in React table explorer
- [x] [Poachable] Reimplement table stats command in React table explorer
- [x] Reimplement refresh command in React table explorer
- [x] Add toggling query panel to React table explorer
- [x] Add query editor for React table explorer
- [x] Add query builder for React table explorer
- [x] Reimplement grouping/ungrouping in query builder for React table explorer
- [x] [Poachable] Reimplement UI for handling `DateTime` query values
- [x] [Poachable] Reimplement saving/loading editor-based queries for React table explorer
- [x] [Poachable] Reimplement saving/loading builder-based queries for React table explorer
- [x] [Poachable] Do not close/clear query builder when refreshing table
- [x] [Poachable] Hook up explorer to refresh events
```

```[tasklist]
### Related Bugs
- [ ] #6681
- [ ] #6680 
- [ ] #6679 
- [ ] #6678 
- [ ] #6676 
- [ ] #6674 
- [ ] #6675 
- [ ] #6506
```
