### ISSUE TITLE
Add native Arm64 support on Windows

### ISSUE THREAD

**Issue by prayaas-a** [microsoft/AzureStorageExplorer#6072]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'm currently using Azure Storage Explorer on a Surface Pro X and finding that the performance is *significantly* worse than on Intel platforms (for example, after clicking Help -> About for the first time, it takes at least 30 seconds for the About dialog box to appear). The experience is subpar and worse than how most apps/programs perform on Windows on Arm.

### Desired Solution

The ideal solution would be a native Arm64 build for Windows. I'm not aware of what all components or dependencies ASE relies on; however, it looks like some form of Electron (which is now available for Arm64 on Windows). AzCopy doesn't appear to be native Arm64 on Windows yet, though it appears Linux and macOS Arm64 support is being built.

### Alternatives and Workarounds

It looks like there's been a "64 bit" (presumably x64) version earmarked for a future release since 2018 - https://github.com/microsoft/AzureStorageExplorer/issues/106. I don't have data but I've read anecdotal reports suggesting that x64 emulation on Windows on Arm is faster, so that could act as a stopgap until the Arm64 version is ready.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/7815
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/7816
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/7862
```

**Comment by MRayermannMSFT** [comment]
@prayaas-a thanks for the request. Windows 10 ARM is on the backlog. We'll use this issue as the main issue for that work.

**Comment by vanillajonathan** [comment]
...and native ARM64 support on Linux! 🐧

**Comment by vanillajonathan** [comment]
> > ...and native ARM64 support on Linux! penguin
> 
> Can you please open a separate issue for this? Thank you.

Alright, I opened #6072!

**Comment by MRayermannMSFT** [comment]
We're going to be shooting for a preview build of Windows ARM64 Storage Explorer in 1.34.0.
