### ISSUE TITLE
Add preview support for CSV, Parquet and Avro

### ISSUE THREAD

**Issue by JoeEdwardsGitHub** [microsoft/AzureStorageExplorer#6153]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/6519
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/6520
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/6844
```

### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Utilising the new preview feature on my data lake

### Desired Solution

As per your request for other file types to support in the preview feature, anyone running a data lake would like to see support for CSV, Parquet and Avro

**Comment by JasonYeMSFT** [comment]
@JoeEdwardsGitHub When you say Data Lake, do you mean Azure Data Lake Gen2 (ADLS Gen2) or Data Lake Store Gen1? We are planning to retire Data Lake Store Gen1 in a few milestones so the preview feature won't be added there.

If you are using ADLS Gen2 and your blobs have file extensions indicating what they are (e.g. .csv, .pqt, etc.), you can add them to the setting to allow previewing them.
![image](https://user-images.githubusercontent.com/39359541/195950704-c64709ff-8414-4cf5-a822-9994f8bb235d.png)

**Comment by JoeEdwardsGitHub** [comment]
Thank you for your response. Yes I am using ADLS Gen2 with hierarchical namespace enabled. Your suggestion works well for CSV, although it would be helpful firstly to let people know this setting exists, secondly to pre-populate it with the 4 default values above, rather than having to re-type them when you want to add a fifth value, and thirdly to add ".csv" as a default, as this seems a non-controversial example of a text file.

However for both ".parquet" ([https://parquet.apache.org/](https://parquet.apache.org/)) and ".avro" ([https://avro.apache.org/](https://avro.apache.org/)) these are not text files, they are column and row based (respectively) data storage formats containing schema metadata, so reading them as plain text does not help. What would be ideal is for the data within them to be rendered as a structured table. Given how much ADLS Gen2 is used for data lakes, and how extremely common these formats are, these would be very helpful features.

**Comment by JasonYeMSFT** [comment]
I am going to repurpose the issue as a feature request for previewing table-like structured data.

**Comment by JasonYeMSFT** [comment]
For anyone interested in this feature, do you know what encoding scheme does your parquet file use? We are evaluating if we want to implement our own decoder for the rle/bit-pack hybrid scheme since the available library doesn't support it right now.

**Comment by JasonYeMSFT** [comment]
How do you feel about parsing the parquet data and display the data as a JSON document? Like in this screenshot (the data is fake data, not PII)
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/39359541/204882159-1ace66bf-028f-4680-93a5-04b98b5a914c.png">

**Comment by JoeEdwardsGitHub** [comment]
@JasonYeMSFT that sounds like a great idea. For the purposes of a preview it's the data you are interested in rather than the layout. JSON can accommodate the same objects and arrays as appear in parquet structs, so that seems very suitable.

Thanks, Joe

**Comment by JasonYeMSFT** [comment]
I have one more question before diving into the details. Could anyone share the average size of parquet file you would like to preview? I need to consider the memory consumption before deciding how to present the data.

**Comment by JoeEdwardsGitHub** [comment]
@JasonYeMSFT in our data lake we have millions of parquet files that are no more than a few kB, however as with any data file they can be any size you like. Most sources recommend they are no larger than 1GB before you split over multiple files.

I think in the scenario of previewing in ASE it is entirely reasonable to set at arbitrary upper limit of file size that can be previewed to a value that would not cause serious performance problems on an average machine. Preview is not suitable for reading massive files, it's for a quick lookup of small to medium-sized files.

**Comment by SqlAndWood** [comment]
I like the idea of being able to preview .parquet files, however json might only be suitable for files less than a specific size (or number of rows). As identified by Jason Ye MSFT, for a large parquet file, I'm not sure JSON is the right preview type.

I realise that json grants the capability of displaying associated metadata (when included in the file).  However, given the request is for a preview, I wouldn't expect this level of detail.

**Comment by JoeEdwardsGitHub** [comment]
I would certainly be happy with @SqlAndWood 's suggestion of the top N rows, so long as it was clearly stated when the rows had been truncated. Choose a value of N that is suitable for an average computer. Metadata at the start would be a useful addition.

The issue with say a tabular (e.g. CSV) format would be structs (nested arrays/objects), which JSON can render easily.

**Comment by MRayermannMSFT** [comment]
For 1.29 we will be starting with CSV.

**Comment by craxal** [comment]
Implementation for all three formats is now complete.
