### ISSUE TITLE
Add support to specify all security features for SAS URIs in Azure Storage Explorer

### ISSUE THREAD

**Issue by SHernanMSFT** [microsoft/AzureStorageExplorer#6361]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

SAS URIs have the capability to express many security constraints, including IP address restrictions. As a popular platform for creating SAS URIs it would be best if Storage Explorer supported the creation of SAS URIs with all security features

### Desired Solution

Support for creating a SAS URI with all (current) securiy features, including, e.g., IPAddress restrictions, and cache control. 

### Alternatives and Workarounds

Create SAS URIs from the portal or through the C# APIs

### Additional Context

Being bearer tokens, SAS URIs have to be carefully controlled, but even still they might get leaked. The ability to create stronger SAS URIs from such a popular platform would be beneficial to everyone. I spoke with Jing Lou directly about this issue.

```[tasklist]
### Tasks
- [x] IP Addresses
- [x] Response Headers
- [x] Encryption Scope
```

**Comment by craxal** [comment]
Currently blocked by https://github.com/Azure/azure-sdk-for-js/issues/25252.

**Comment by craxal** [comment]
Waiting for new release of @azure/data-tables around April 6.
