### ISSUE TITLE
Queue extension updates

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#6455]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/6456
- [x] Upgrade queue dialogs to use `<se-dialog-window>`
- [x] Update queue extension to use webpack
- [x] Remove use of old SDK from queue extension
- [x] Use data table component instead of datatables.net directly
- [x] Update data table component to allow data source to provide total items explicitly
```

```[tasklist]
### Related Bugs
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/6380
```
