### ISSUE TITLE
React component fixes

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#6506]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/6405
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/6508
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/6507
- [ ] #6635
```
