### ISSUE TITLE
Support previewing audio files

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6642]
Audio file types
- .mp3
- .wav

Taken from here: https://github.com/microsoft/AzureStorageExplorer/issues/6627

```[tasklist]
### Tasks
- [x] CELA review codecs (Jason, actually this is not need)
- [x] PR with Electron at MSFT team (Jason)
- [x] Update build scripts/pipeline to use new FFmpeg flavor (Jason)
- [x] Actual audio preview (Richard)
```

**Comment by JasonYeMSFT** [comment]
Electron prep work is done in 1.30.0.
