### ISSUE TITLE
Migrate file share explorer to react

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7154]
Migrate the file share explorer to a React version. Should support:

- All existing scenarios for files
- All existing scenarios for directories
- All existing scenarios for snapshots
- Global sort
- Column reordering
- Load all setting (if #7157 done in time)
- Support Alt+Enter shortcut for viewing properties #4416

Ensure that https://github.com/microsoft/AzureStorageExplorer/issues/6945 is resolved/does not repro in React.

Redesign/refactor old code (for example, the "location" objects) as appropriate.

```[tasklist]
### Tasks
- [x] Panel scaffolding
- [x] Data grid
- [x] Data source
- [x] Toolbar
- [x] Prefix search
- [x] Commands
- [x] Snapshots
- [x] Global sort
- [x] Column customization
- [x] Switch download/preview setting when opening items
- [ ] #7157
- [x] #4416
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/6945
- [x] Remove old explorer
```
