### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by JORGEGO** [microsoft/AzureStorageExplorer#7344]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Platform

Windows

### OS Version

Windows 11 Pro 22621.2361

### Bug Description

I have never been this error let me show in a picture

![image](https://github.com/microsoft/AzureStorageExplorer/assets/3842104/b6162af3-5da2-4ad1-8984-3d78074756f8)

### Steps to Reproduce

1. Launch MASE and eveytime the same

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/3842104/43568066-6f2d-4854-bb85-0b3c662e8f95)

```[tasklist]
### Tasks
```

**Comment by JORGEGO** [comment]
More information:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/3842104/c1883045-5495-410f-8c17-b67d307fd2d8)

**Comment by JORGEGO** [comment]
![image](https://github.com/microsoft/AzureStorageExplorer/assets/3842104/027ff51f-7662-4d6e-b419-316647bf1abb)

**Comment by JORGEGO** [comment]
I have the default browser to MIcrosoft Windows Edge, but it not opened

**Comment by JORGEGO** [comment]
Moved to 1.29.2 and works

**Comment by JORGEGO** [comment]
So my conclusions in my cas is version 64 bit error, and when I return to 32bit works

**Comment by JORGEGO** [comment]
Fixed, the problem was in my last Visual Studio 2022 professional update. Was not correct... seems, after uninstall and install again from scratch all works, so close the issue
