### ISSUE TITLE
Cached Table meta data

### ISSUE THREAD

**Issue by ToddChitt** [microsoft/AzureStorageExplorer#7427]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.2(94)

### Architecture

x64

### Storage Explorer Build Number

10231003.6

### Platform

All

### OS Version

Windows 10

### Bug Description

Azure table meta data is cached somewhere.

### Steps to Reproduce

1) Create an Azure table.
2) Load that table with data such that it will add columns as needed.
3) Delete the table.
4) Wait a minute or so for the table to REALLY get deleted.
5) Re-create the table using the same name.

### Actual Experience

I see a table with the same metadata columns as the one I just deleted, instead of a clean, empty table with no columns

### Expected Experience

I expect to get a clean, empty table with only the key columns, no custom columns that I added in the old one. What I SEE is a table with columns the same as the one I just deleted. 

### Additional Context

A co-worker with access to the same table sees a table with NO columns. That list of columns is ONLY seen by me, indicating that its metadata is cached somewhere, either in the tool or on my machine.

**Comment by craxal** [comment]
If you right-click any table column header and select Reset Columns, does that help?

**Comment by MRayermannMSFT** [comment]
@ToddChitt yes, the columns are saved between sessions on a per table basis. That way, as you rearrange, hide, and resize columns, even after restarting the Storage Explorer, all those customizations are restored.

In your re-created table though, once you've imported some data/added some entities, you should be able to right click on any of the column headers and select "Reset Columns" to clear out the columns that existed for entities in the old version of the table but not in entities in the new version of the table.

**Comment by ToddChitt** [comment]
If the table is empty, as it is when I first create it, I cannot do a
'Reset Column'. There must first be data in it. Yes, I can manually insert
a row, Reset the Columns, then Delete that row. But that's 'defect support
system'.
Question:
WHY was it decided that when creating a table of the same name as one just
deleted it should pick up cached columns? For me, the REASON I'm dropping
that table is because the columns are all messed up and I can't simply
delete a column that contains data. I want a clean, fresh table. The fact
that my co-worker see a clean, fresh table and I do not is both confusing
and frustrating.

-Todd

**Comment by craxal** [comment]
@ToddChitt We understand, and we agree that it can be confusing.

Storage Explorer stores data about a table's columns using the table's URL as a key. When you create a table with the same name as a table that was just deleted, they will have the same URL. Unfortunately, there really is no way to distinguish either table from each other. It was not expected that creating a table with the same name as a deleted one would be a common occurrence.

A fix for this should be fairly straightforward. We just need to delete the column data with the table.

**Comment by MRayermannMSFT** [comment]
@ToddChitt 

First, just to make sure it is clear, the columns you see in Storage Explorer in the new version of the table are not "real". They are simply there as a display convenience. Ultimately, the columns in a table are defined by the properties that exist on the entities in the table. So if there's any worry about Storage Explorer creating columns that don't exist when you open the old table, understand that there is no need to worry that.

> WHY was it decided that when creating a table of the same name as one just deleted it should pick up cached columns?

If the table is deleted outside of Storage Explorer, there isn't a way for Storage Explorer to know that. As far as it knows, it is the same table but now with 0 entities. And if that is the case, then it is very much convenient if Storage Explorer maintains the column customizations, so once new entities are added, those customizations are still active.

If the table was deleted in Storage Explorer, then sure, that is a fair ask, and I've open a feature request for that [here](https://github.com/microsoft/AzureStorageExplorer/issues/7449). However, given this is the first time we've heard of this confusion popping up I cannot promise that we will address it. I can see other situations in which someone deletes a table and then recreate it, but would want to still have their customized columns restored. We'll need to talk more about it as a team. Feel free to follow the feature request for updates.

> There must first be data in it. 

Yes, perhaps there should be a way to reset columns in the absence of entities. I've created a feature request for that [here](https://github.com/microsoft/AzureStorageExplorer/issues/7450). Again, we'll discuss this more as a team, and you can follow it for updates.

**Comment by MRayermannMSFT** [comment]
Going to close this now given the lack of further response. Please feel free to share further feedback/thoughts on either of the two linked issues (if relevant to them) or in a new issue. Thanks.
