### ISSUE TITLE
Select Columns Dialog Usability & Accessibility Needs Updating

### ISSUE THREAD

**Issue by MRayermannMSFT** [Microsoft/AzureStorageExplorer#7428]
```[tasklist]
## Tasks
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/7681
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/7682
- [x] https://github.com/microsoft/AzureStorageExplorer/issues/7683
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/7671
```
