### ISSUE TITLE
Re-evaulate best practices for dialogs

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7518]
```[tasklist]
## Tasks
- [ ] Reconfirm that our Content-Security-Policy is most restrictive as possible, and that all dialogs use the policy if possible
- [ ] Determine where `script` elements are best declared (in `head`, start of `body`, end of `body`)
- [ ] Determine if `script` elements to load index fields are best done as a `script` element with a `src` attribute, or with an inline script that calls `require`.
- [ ] Dialog ID formats
```

**Comment by craxal** [comment]
I don't see us getting around to this anytime soon, and I'm not sure if there are any real problems this will solve. So we're just going to close.
