### ISSUE TITLE
Support Windows OS Authentication Broker (WAM) for Sign-In

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#8059]
Notes:
- Only works on Windows 10/11, macOS coming soon (maybe not in time for milestone this item is assigned)
- Does not work if Storage Explorer is "Run as [Another User]"
- Identity team will do TS changes of adding window handle in property bag parameter
- Help them test after they add it
- Try to redirect users to [Errors associated with Web Account Manager (WAM) - Microsoft Authentication Library for .NET | Microsoft Learn](https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/exceptions/wam-errors)

```[tasklist]
## TODO
- [x] Help identity team make and test TS changes
- [x] Check in support to main
- [x] Tell CTI
- [x] Update TSG for sign in issues with above link
- [x] Update "Understanding Sign-in" doc"
```

**Comment by jinglouMSFT** [comment]
KPI requires this to be closed by 9/30/24.

**Comment by craxal** [comment]
Implementation for Windows is already present in 1.35.0. macOS is not currently supported, so we're waiting for support. Once we hit 90% traffic, and the S360 issue resolves, we can close this item.
