### ISSUE TITLE
Routine Tasks for 1.36.0

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#8102]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/8203
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/8108
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/8107
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/8106
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/8105
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/8104
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/8103
- [ ] https://github.com/microsoft/AzureStorageExplorer/issues/8123
```
