### ISSUE TITLE
Revist Manage Access Dialog

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#955]
We need to revisit the Manage Access Dialog, aka: 
![image](https://user-images.githubusercontent.com/41351993/49194020-6b09b680-f3bc-11e8-89c8-80997d8d5dec.png)

Issues brought up by the service team:

- [ ] No way to search for users or groups, all we do is validate (post 1.6.1)
- [x] No way to promote someone to be the owner (post 1.6.1)
- [x] Verify that adding a group to a ADLS Gen2 ACL Works #954  
- [ ] Manage Access Dialog Does not Change Inputted OIDs to UPNs #957 
- [x] When Groups are Added to the Manage Access Dialog, You Can't Give Them Permissions #958 
- [ ] Platform team has requested that we offer some sort of Manage Access experience when Storage accounts are attached with name and key. (post 1.6.1)

We should meet with UI team and figure out if we want to move to a multi-panel dialog or do some other sort of UI change to address these concerns.
