### ISSUE TITLE
Add RBAC support for queues

### ISSUE THREAD

**Issue by cbrooksmsft** [microsoft/AzureStorageExplorer#975]
**Storage Explorer Version**: 1.6.0
**Platform/OS**: Windows
**Architecture**:
**Regression From**: N/A

**Bug description**
Using AAD/RBAC to connect to storage, queue listing fails

**Steps to Reproduce**
List the minimal steps clearly and concisely to reproduce the behavior:
1. grant user "Reader" role (which include queue read permissions) at scope that covers a storage account
2. expand "Queues" node

**Expected Experience**
Queues are listed

**Actual Experience**
See error"  "Unable to list resources in account due to inadequate permissions.  Permission to list containers or to list account keys is required.  Contact your subscription administrator to resolve the issue."

**Additional Context**
I am able to list queues as this user with REST API.

## Tasks
- [x] Move queues to extension
  - [x] Move tree node and actions to extension
  - [x] Move editor to extension
  - [x] Move dialogs to extension
- [x] Refactor to use `@azure/storage-queue` v12 library
- [x] Refactor queues to use `IQueueServiceConnection` and `IQueueConnection`
- ~~Refactor accounts to use `IStorageAccountConnection`~~
- [x] Consolidate duplicate types in `se-azure`
- [x] Fix detach for Quick Access (#2782)
- [x] Support no-key mode
- [x] Migrate existing Quick Access nodes to newer format

**Comment by jinglouMSFT** [comment]
Queues using RBAC is not supported in this release of storage explorer.

**Comment by JakobGSvendsen** [comment]
This works if user is Owner, but I cant seem to find what actions you are making as it is not just a list.
This also is the same for file shraes, table and queue storage.

I just want to make a custom role to support this until you get it fixed, as this is blocking many devs at my customer's tests etc, as they cannot read the result in the storage accounts in test and prod, as theyu are not allowed to have more than read access.

So what action is required?

for example, storage contributor is not enough either.  you can see its actions here:
https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-account-contributor

**Comment by craxal** [comment]
Tasks:
- [ ] Move queues to extension
  - [ ] Move tree node and actions to extension
  - [ ] Move editor to extension
  - [ ] Move dialogs to extension
- [ ] Refactor accounts to use `IStorageAccountConnection`
- [ ] Consolidate duplicate types in `se-azure`
